projects:
  nutrilevel:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: prnb5fvtafab7oplki643c253u
      endpoints:
        prod: >-
          https://tyawkccqyra5fm2qalb5ybs7m4.appsync-api.us-west-2.amazonaws.com/graphql
