// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:476ff3eb-b34f-4e38-ad2a-ab22d3e4507a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_BUBlmXYpU",
    "aws_user_pools_web_client_id": "5q9sqj1o5nhd30oiali9i0lnh0",
    "aws_appsync_graphqlEndpoint": "https://tyawkccqyra5fm2qalb5ybs7m4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
